name: Deploy til Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 51.103.212.67
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASSWORD }}
          script_stop: false
          script: |
              cd /home/Miho/turbine-iot && git pull && pip install -r requirements.txt --break-system-packages && pkill -f TurbineApi.py || true && setsid nohup python3 TurbineApi.py > app.log 2>&1 < /dev/null & echo "OK"
